<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EMEA-TUN-LP0709" name="CalcTest" tests="1" failures="1" timestamp="2 Dec 2018 23:15:16 GMT" time="29.122" errors="0">
  <testcase name="verifyTwoValueOperation" time="1.035" classname="LogMeInCalcTest.CalculatorTestClass">
    <failure type="java.lang.AssertionError" message="expected [ERR] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [ERR] but found [1]
	at LogMeInCalcTest.CalculatorTestClass.verifyTwoValueOperation(CalculatorTestClass.java:160)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyTwoValueOperation -->
</testsuite> <!-- CalcTest -->
